### PR TITLE
Update package-lock.json

### PR DESCRIPTION
**Pull request by Bassmala**

### CODE REVIEW

**Comment by Bassmala** [comment]
@shieldfy fix lodash

**Comment by Bassmala** [comment]
@shieldfy fix NoSQL injection

**Comment by Bassmala** [comment]
@shieldfy fix NoSQL

**Comment by Bassmala** [comment]
@shieldfy fix config/passport.js

**Comment by Bassmala** [comment]
@shieldfy fix sequalize

**Comment by Bassmala** [comment]
@shieldfy  fix controllers/user.js

**Comment by BassmalaHafez** [comment]
@shieldfy details

**Pull request closed without merging**
